# This is a basic workflow to help you get started with Actions

name: Exercicio 02 CLI

# Controls when the action will run. 
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
env:
  WORKFLOW_VAR: 'uma variável qualquer'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NODE_VERSION: 12
      JOB_VAR: 'uma variável no escopo'
      
    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.4
    
    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ env.NODE_VERSION }}
    
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.2.3
      with:
        name: app-do-usuario
        path: .
        if-no-files-found: error
        retention-days: 3
