name: Exercicio 01 CI
on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs1:
  job1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Rodando um simples script
        run: date
jobs2:
  job1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Rodando um simples script
        run: date
jobs3:
  job1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Rodando um simples script
        run: date
