
name: Expandindo CLI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run a one-line script
        run: echo A data de agora é `date`
        
      - name: Testar WGET
        run: wget http://www.google.com
    

