# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 14
      uses: actions/setup-node@v1
      with:
        node-version: 14
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test --if-present
  
  deploy:
    runs-on: ubuntu-latest
    env:
      DB_URI: $${{ secrets.DB_URI }}
      NODE_ENV: production
      
    needs: [build]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          # Full git history is needed to build on Heroku
          fetch-depth: 0
      
      - name: Login Heroku
        uses: akhileshns/heroku-deploy@v3.10.9 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: app-impacta-wellingtoncps
          heroku_email: wellington.aied@gmail.com
          justlogin: true
      
      - name: Set Heroku remote
        run: heroku git:remote -a app-impacta-pedrolacerda
      
      - name: Set env variables
        run: |
          heroku config:set NODE_ENV=${{ env.NODE_ENV }}
          heroku config:set MONGODB_URI=${{ env.DB_URI }}
      
      - name: Push code to Heroku
        run: git push heroku main
